DROP TABLE TB_CART;
DROP TABLE TB_STORE;
DROP TABLE TB_ADDRESS;

DROP SEQUENCE SEQ_TB_ADDRESS_ID;
DROP SEQUENCE SEQ_TB_CART_ID;
DROP SEQUENCE SEQ_TB_STORE_ID;

CREATE TABLE TB_CART (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP,
    CODE NUMBER(19,0) NOT NULL,
    STORE_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_STORE (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    STORE_ALIAS VARCHAR2(25),
    STORE_NAME VARCHAR2(255) NOT NULL,
    ADDRESS_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ADDRESS (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP DEFAULT SYSDATE,
    UPDATED TIMESTAMP,
    ADDRESS_CITY VARCHAR2(255),
    ADDRESS_STREET_NAME VARCHAR2(255),
    ADDRESS_NUMBER NUMBER(10,0),
    ADDRESS_POSTAL_CODE VARCHAR2(9 CHAR),
    ADDRESS_UF VARCHAR2(3),
    PRIMARY KEY (ID)
);

ALTER TABLE TB_CART ADD CONSTRAINT UK_TB_CART_CODE UNIQUE (CODE);
ALTER TABLE TB_CART ADD CONSTRAINT FK_TB_STORE FOREIGN KEY (STORE_ID) REFERENCES TB_STORE;
ALTER TABLE TB_STORE ADD CONSTRAINT FK_TB_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES TB_ADDRESS;

CREATE SEQUENCE SEQ_TB_ADDRESS_ID START WITH 1 INCREMENT BY  10;
CREATE SEQUENCE SEQ_TB_CART_ID START WITH 1 INCREMENT BY  10;
CREATE SEQUENCE SEQ_TB_STORE_ID START WITH 1 INCREMENT BY  10;
