CREATE TABLE TB_CART (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP,
    CODE NUMBER(19,0) NOT NULL,
    STORE_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_STORE (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    STORE_ALIAS VARCHAR2(25 CHAR),
    STORE_NAME VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_ADDRESS (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    ADDRESS_CITY VARCHAR2(255 CHAR),
    ADDRESS_NUMBER NUMBER(10,0),
    ADDRESS_POSTAL_CODE NUMBER(10,0),
    ADDRESS_UF VARCHAR2(3 CHAR),
    PRIMARY KEY (ID)
);

ALTER TABLE TB_CART ADD CONSTRAINT UK_TB_CART_CODE UNIQUE (CODE);
ALTER TABLE TB_CART ADD CONSTRAINT FK_TB_STORE FOREIGN KEY (FK_STORE) REFERENCES TB_STORE;
ALTER TABLE TB_STORE ADD CONSTRAINT FK_TB_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES TB_ADDRESS;

CREATE SEQUENCE SEQ_TB_ADDRESS_ID START WITH 1 INCREMENT BY  10;
CREATE SEQUENCE SEQ_TB_CART_ID START WITH 1 INCREMENT BY  10;
CREATE SEQUENCE SEQ_TB_STORE_ID START WITH 1 INCREMENT BY  10;