CREATE TABLE TB_CART (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    UPDATED TIMESTAMP,
    CODE NUMBER(19,0) NOT NULL,
    STORE_ID NUMBER(19,0) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TB_STORE (
   ID NUMBER(19,0) NOT NULL,
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    STORE_ALIAS VARCHAR2(25 CHAR),
    STORE_NAME VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE TB_CART ADD CONSTRAINT UK_TB_CART_CODE UNIQUE (CODE);
ALTER TABLE TB_CART ADD CONSTRAINT FK_TB_STORE FOREIGN KEY (FK_STORE) REFERENCES TB_STORE;
   
CREATE SEQUENCE SEQ_TB_CART_ID START WITH 1 INCREMENT BY  10;
CREATE SEQUENCE SEQ_TB_STORE_ID START WITH 1 INCREMENT BY  10;